version: "3.9"
services:
  java:
    image: omarsater/private-repo:react-v1.1.4
    environment:
    ports:
      - "9000:8080"
    depends_on:
      - database
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASWORD=my-pwd

